server:
  port: ${APPLICATION_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: fast-food-soat

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:P@ssw0rd}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    serialization:
      indent_output: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

security:
  auth:
    token:
      expiration: ${AUTH_TOKEN_EXPIRATION:43200}

