server:
  port: 8080

spring:
  application:
    name: fastfood-soat

  datasource:
    url: jdbc:postgresql://localhost:5432/fastfood_soat
    username: ${POSTGRES_FASTFOOD_USERNAME}
    password: ${POSTGRES_FASTFOOD_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jackson:
    serialization:
      indent_output: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha


